### ISSUE TITLE
运行yolov4 和 yolov5 失败

### ISSUE THREAD

**Issue by czstudio** [gmt710/AlphaPose_yolovx#6]
（1）使用yolov3检测没有问题，使用yolov4检测出现出错误
```
(torch) D:\Code\AlphaPose_yolovx-master>python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --detector yolov4  --vis --showbox
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 175, in <module>
    det_loader = DetectionLoader(input_source, get_detector(args), cfg, args, batchSize=args.detbatch, mode=mode, queueSize=args.qsize)
  File "D:\Code\AlphaPose_yolovx-master\detector\apis.py", line 17, in get_detector
    from detector.yolov4_api import YOLOV4Detector as det
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov4_api.py", line 15, in <module>
    from yolo_v4.detect import Detector
  File "D:\Code\AlphaPose_yolovx-master\detector\yolo_v4\detect.py", line 4, in <module>
    from yolov4.tool.class_names import COCO_NAMES
ModuleNotFoundError: No module named 'yolov4'
```
（2）使用yolov5检测出现出错误
```
(torch) D:\Code\AlphaPose_yolovx-master>python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_2x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/ --detector yolov5  --vis --showbox
Loading YOLOV5 model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]Fusing layers...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\learn\Anaconda3\envs\torch\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\learn\Anaconda3\envs\torch\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\AlphaPose_yolovx-master\alphapose\utils\detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 102, in images_detection
    dets = self.dynamic_write_results(prediction, self.confidence,
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 122, in dynamic_write_results
    dets = self.write_results(prediction.clone(), confidence, num_classes, nms, nms_conf)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 218, in write_results
    ious = bbox_iou(max_detections[-1], image_pred_class[1:], x1y1x2y2=False, CIoU=True)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5\utils\general.py", line 210, in bbox_iou
    b1_x1, b1_x2 = box1[0] - box1[2] / 2, box1[0] + box1[2] / 2
IndexError: index 2 is out of bounds for dimension 0 with size 1
```

**Comment by gmt710** [comment]
Hello, can you follow my blog ?

**Comment by czstudio** [comment]
windows环境不可以吗？

**Comment by gmt710** [comment]
you can try it.

**Comment by czstudio** [comment]
windows可以运行，但是yolov5会出错：
` Loading YOLOV5 model..
Loading pose model from pretrained_models/fast_res50_256x192.pth...
  0%|                                                                                           | 0/16 [00:00<?, ?it/s]Fusing layers...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\learn\Anaconda3\envs\py38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\learn\Anaconda3\envs\py38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\AlphaPose_yolovx-master\alphapose\utils\detector.py", line 223, in image_detection
    dets = self.detector.images_detection(imgs, im_dim_list)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 102, in images_detection
    dets = self.dynamic_write_results(prediction, self.confidence,
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 122, in dynamic_write_results
    dets = self.write_results(prediction.clone(), confidence, num_classes, nms, nms_conf)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5_api.py", line 218, in write_results
    ious = bbox_iou(max_detections[-1], image_pred_class[1:], x1y1x2y2=False, CIoU=True)
  File "D:\Code\AlphaPose_yolovx-master\detector\yolov5\utils\general.py", line 210, in bbox_iou
    b1_x1, b1_x2 = box1[0] - box1[2] / 2, box1[0] + box1[2] / 2
IndexError: index 2 is out of bounds for dimension 0 with size 1`

**Comment by abc844** [comment]
I'm having a similar problem. Did you successfully solve it?

**Comment by abc844** [comment]
@czkyx

**Comment by abc844** [comment]
I rewrote the iou and successfully solved the problem.

**Comment by gmt710** [comment]
Ok, thank you, I will close this issue.
If there are any problems, please feel free to reopen it.
